import { EdiVersion, EdiSegment, EdiElement, ElementType, EdiDelimiter } from "../../new_parser/entities";
import * as vscode from "vscode";
import { EdiSchema } from "../../schemas/schemas";
import * as constants from "../../cat_const";
import Utils from "../../utils/utils";
import { EdiUtils } from "../../utils/ediUtils";
import { DiagBase } from "../diagBase";

export class Diag850 extends DiagBase {

    private _tableDFA = {
        "ROOT": {
            "ISA": "ROOT_ISA",
        },
        "ROOT_ISA": {
            "GS": "ROOT_GS",
        },
        "ROOT_GS": {
            "ST": "ROOT_ST",
        },
        "ROOT_ST": {
            "BEG": "ROOT_BEG",
        },
        "ROOT_BEG": {
            "CUR": "ROOT_CUR",
            "REF": "ROOT_REF",
            "PER": "ROOT_PER",
            "FOB": "ROOT_FOB",
            "CSH": "ROOT_CSH",
            "SAC": "SAC_SAC",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
        },
        "ROOT_CUR": {
            "REF": "ROOT_REF",
            "PER": "ROOT_PER",
            "FOB": "ROOT_FOB",
            "CSH": "ROOT_CSH",
            "SAC": "SAC_SAC",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
        },
        "ROOT_REF": {
            "REF": "ROOT_REF",
            "PER": "ROOT_PER",
            "FOB": "ROOT_FOB",
            "CSH": "ROOT_CSH",
            "SAC": "SAC_SAC",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
        },
        "ROOT_PER": {
            "PER": "ROOT_PER",
            "FOB": "ROOT_FOB",
            "CSH": "ROOT_CSH",
            "SAC": "SAC_SAC",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
        },
        "ROOT_FOB": {
            "CSH": "ROOT_CSH",
            "SAC": "SAC_SAC",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
            "PID":"ROOT_PID",
            "TXI":"ROOT_TXI",
            "N9":"N9_N9",
        },
        "ROOT_CSH": {
            "SAC": "SAC_SAC",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
            "PID":"ROOT_PID",
            "TXI":"ROOT_TXI",
            "N9":"N9_N9",
        },
        "SAC_SAC": {
            "SAC": "SAC_SAC",
            "CUR": "SAC_CUR",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
            "PID":"ROOT_PID",
            "TXI":"ROOT_TXI",
            "N9":"N9_N9",
        },
        "SAC_CUR": {
            "SAC": "SAC_SAC",
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
            "PID":"ROOT_PID",
            "TXI":"ROOT_TXI",
            "N9":"N9_N9",
        },
        "ROOT_ITD": {
            "ITD": "ROOT_ITD",
            "DTM": "ROOT_DTM",
            "PID":"ROOT_PID",
            "TXI":"ROOT_TXI",
            "N9":"N9_N9",
        },
        "ROOT_DTM": {
            "DTM": "ROOT_DTM",
            "PID":"ROOT_PID",
            "TXI":"ROOT_TXI",
            "N9":"N9_N9",
            "N1":"N1_N1,"
        },
        "ROOT_PID": {
            "TXI":"ROOT_TXI",
            "N9":"N9_N9",
            "N1":"N1_N1,"
        },
        "ROOT_TXI": {
            "N9":"N9_N9",
            "N1":"N1_N1",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N9_N9": {
            "N9":"N9_N9",
            "DTM":"N9_DTM",
            "N1":"N1_N1",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N9_DTM": {
            "N9":"N9_N9",
            "DTM":"N9_DTM",
            "N1":"N1_N1",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_N1": {
            "N1":"N1_N1",
            "N2":"N1_N2",
            "N3":"N1_N3",
            "N4":"N1_N4",
            "REF":"N1_REF",
            "PER":"N1_PER",
            "TD5":"N1_TD5",
            "TD4":"N1_TD4",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_N2": {
            "N1":"N1_N1",
            "N3":"N1_N3",
            "N4":"N1_N4",
            "REF":"N1_REF",
            "PER":"N1_PER",
            "TD5":"N1_TD5",
            "TD4":"N1_TD4",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_N3": {
            "N1":"N1_N1",
            "N4":"N1_N4",
            "REF":"N1_REF",
            "PER":"N1_PER",
            "TD5":"N1_TD5",
            "TD4":"N1_TD4",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_N4": {
            "N1":"N1_N1",
            "REF":"N1_REF",
            "PER":"N1_PER",
            "TD5":"N1_TD5",
            "TD4":"N1_TD4",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_REF": {
            "N1":"N1_N1",
            "REF":"N1_REF",
            "PER":"N1_PER",
            "TD5":"N1_TD5",
            "TD4":"N1_TD4",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_PER": {
            "N1":"N1_N1",
            "PER":"N1_PER",
            "TD5":"N1_TD5",
            "TD4":"N1_TD4",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_TD5": {
            "N1":"N1_N1",
            "TD4":"N1_TD4",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "N1_TD4": {
            "N1":"N1_N1",
            "PO1":"PO1_PO1",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "PO1_PO1": {
            "PO1":"PO1_PO1",
            "CUR":"PO1_CUR",
            "PO3":"PO1_PO3",
            "CTP":"PO1_CTP_CTP",
            "MEA":"PO1_MEA",
            "PID":"PO1_PID_PID",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "PO1_CUR": {
            "PO1":"PO1_PO1",
            "PO3":"PO1_PO3",
            "CTP":"PO1_CTP_CTP",
            "MEA":"PO1_MEA",
            "PID":"PO1_PID_PID",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "PO1_PO3": {
            "PO1":"PO1_PO1",
            "CTP":"PO1_CTP_CTP",
            "MEA":"PO1_MEA",
            "PID":"PO1_PID_PID",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "PO1_CTP_CTP": {
            "PO1":"PO1_PO1",
            "CTP":"PO1_CTP_CTP",
            "CUR":"PO1_CTP_CUR",
            "MEA":"PO1_MEA",
            "PID":"PO1_PID_PID",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "PO1_CTP_CUR": {
            "PO1":"PO1_PO1",
            "CTP":"PO1_CTP_CTP",
            "MEA":"PO1_MEA",
            "PID":"PO1_PID_PID",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "PO1_MEA": {
            "PO1":"PO1_PO1",
            "PID":"PO1_PID_PID",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },    
        "PO1_PID_PID": {
            "PO1":"PO1_PO1",
            "PID":"PO1_PID_PID",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_REF": {
            "PO1":"PO1_PO1",
            "REF":"PO1_REF",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SAC_SAC": {
            "PO1":"PO1_PO1",
            "SAC":"PO1_SAC_SAC",
            "CUR":"PO1_SAC_CUR",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SAC_CUR": {
            "PO1":"PO1_PO1",
            "SAC":"PO1_SAC_SAC",
            "FOB":"PO1_FOB",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_FOB": {
            "PO1":"PO1_PO1",
            "SDQ":"PO1_SDQ",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SDQ": {
            "PO1":"PO1_PO1",
            "DTM":"PO1_DTM",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_DTM": {
            "PO1":"PO1_PO1",
            "TXI":"PO1_TXI",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_TXI": {
            "PO1":"PO1_PO1",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_QTY_QTY": {
            "PO1":"PO1_PO1",
            "QTY":"PO1_QTY_QTY",
            "SCH":"PO1_SCH_SCH",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SCH_SCH": {
            "PO1":"PO1_PO1",
            "SCH":"PO1_SCH_SCH",
            "REF":"PO1_SCH_REF",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SCH_REF": {
            "PO1":"PO1_PO1",
            "SCH":"PO1_SCH_SCH",
            "REF":"PO1_SCH_REF",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_PKG_PKG": {
            "PO1":"PO1_PO1",
            "PKG":"PO1_PKG_PKG",
            "MEA":"PO1_PKG_MEA",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_PKG_MEA": {
            "PO1":"PO1_PO1",
            "PKG":"PO1_PKG_PKG",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N9_N9": {
            "PO1":"PO1_PO1",
            "N9":"PO1_N9_N9",
            "MSG":"PO1_N9_MSG",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N9_MSG": {
            "PO1":"PO1_PO1",
            "N9":"PO1_N9_N9",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_N1": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "N2":"PO1_N1_N2",
            "N3":"PO1_N1_N3",
            "N4":"PO1_N1_N4",
            "REF":"PO1_N1_REF",
            "PER":"PO1_N1_PER",
            "TD5":"PO1_N1_TD5",
            "TD4":"PO1_N1_TD4",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_N2": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "N3":"PO1_N1_N3",
            "N4":"PO1_N1_N4",
            "REF":"PO1_N1_REF",
            "PER":"PO1_N1_PER",
            "TD5":"PO1_N1_TD5",
            "TD4":"PO1_N1_TD4",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_N3": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "N4":"PO1_N1_N4",
            "REF":"PO1_N1_REF",
            "PER":"PO1_N1_PER",
            "TD5":"PO1_N1_TD5",
            "TD4":"PO1_N1_TD4",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_N4": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "REF":"PO1_N1_REF",
            "PER":"PO1_N1_PER",
            "TD5":"PO1_N1_TD5",
            "TD4":"PO1_N1_TD4",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_REF": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "REF":"PO1_N1_REF",
            "PER":"PO1_N1_PER",
            "TD5":"PO1_N1_TD5",
            "TD4":"PO1_N1_TD4",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_PER": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "PER":"PO1_N1_PER",
            "TD5":"PO1_N1_TD5",
            "TD4":"PO1_N1_TD4",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_TD5": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "TD4":"PO1_N1_TD4",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_N1_TD4": {
            "PO1":"PO1_PO1",
            "N1":"PO1_N1_N1",
            "SLN":"PO1_SLN_SLN",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SLN_SLN": {
            "PO1":"PO1_PO1",
            "SLN":"PO1_SLN_SLN",
            "MSG":"PO1_SLN_MSG",
            "DTM":"PO1_SLN_DTM",
            "N9":"PO1_SLN_N9_N9",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SLN_MSG": {
            "PO1":"PO1_PO1",
            "SLN":"PO1_SLN_SLN",
            "DTM":"PO1_SLN_DTM",
            "N9":"PO1_SLN_N9_N9",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SLN_DTM": {
            "PO1":"PO1_PO1",
            "SLN":"PO1_SLN_SLN",
            "N9":"PO1_SLN_N9_N9",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "PO1_SLN_N9_N9": {
            "PO1":"PO1_PO1",
            "SLN":"PO1_SLN_SLN",
            "N9":"PO1_SLN_N9_N9",
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "CTT_CTT": {            
            "CTT":"CTT_CTT",
            "AMT":"CTT_AMT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "CTT_AMT": {            
            "CTT":"CTT_CTT",
            "SE":"ROOT_SE",
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "ROOT_SE": {            
            "GE":"ROOT_GE",
            "IEA":"ROOT_IEA",
        },
        "ROOT_GE": {            
            "IEA":"ROOT_IEA",
        },        
       
    }

    /**
     * Usually only return array with 1 element.
     * @returns 
     */
    public runHierarchyDiag(): vscode.Diagnostic[] {
        let statusDFA = "ROOT";
        let rtn: vscode.Diagnostic[] = [];
        for (let seg of this._segs) {

            if (statusDFA == "ROOT_IEA") {
                // Even after UNZ, we still get input ...
                rtn.push(
                    new vscode.Diagnostic(
                        EdiUtils.getSegmentRange(this._document, seg),
                        `Cannot add segments after IEA segment`,
                        vscode.DiagnosticSeverity.Error
                    )
                );
                return rtn;
            }

            // Even one Hierarchy Error should stop the diagnose, because it's meaningless to dig deeper
            if (this._tableDFA[statusDFA][seg.id]) { // "Status => Input" exsits
                seg.newStatusDFA = statusDFA = this._tableDFA[statusDFA][seg.id];
                seg.translateToLayerIds();
            } else {
                // make sure here is using the previous statusDFA
                let strExpected = Object.keys(this._tableDFA[statusDFA]).join(',')
                // "Wrong ${seg.id} for DFA Status:${statusDFA}"
                rtn.push(new vscode.Diagnostic(
                    EdiUtils.getSegmentRange(this._document, seg),
                    `Wrong segment ${seg.id} for last syntax status: ${statusDFA}, expected: ${strExpected}`,
                    vscode.DiagnosticSeverity.Error

                ));
                return rtn;
            }
            //   diagnostic.code = elementError.code;
            //   diagnostics.push(diagnostic);

        }

        return rtn;
    }

}