import * as vscode from "vscode";
import { EdiSchema } from "../../schemas/schemas";
import * as constants from "../../cat_const";
import Utils, { StringBuilder } from "../../utils/utils";
import { EdiUtils } from "../../utils/ediUtils";
import { DocInfoBase } from "../../info/docInfoBase";
import { Info_810 } from "../../info/info_810";
import { ConvertPattern, X12, XML, versionKeys } from "../../cat_const";
import { create } from "xmlbuilder2";
import { format } from "date-fns";
import { CUtilX12 } from "../../utils/cUtilX12";
import { XMLBuilder } from "xmlbuilder2/lib/interfaces";
import { ConvertErr, EdiSegment } from "../../new_parser/entities";
import { ConverterBase } from "../converterBase";
import { ASTNode } from "../../new_parser/syntaxParserBase";
import utils from "../../utils/utils";
import { TidyContact } from "../xmlTidy/TidyCommon";


/**
 * No need to make singleton because parserUtil already assured it
 */
export class Cvt_865_OrderConfirm extends ConverterBase {
    protected _convertErrs: ConvertErr[];
    constructor(astTree: ASTNode) {
        super(astTree);
    }


    public toXMLCheck(document?: vscode.TextDocument): vscode.Diagnostic[] {
        this._document = document;
        this._clearDiags(); // clear previouse check results

        this._chkUsageIndicator();
        return this._cvtDiags;
    }

    public toXML(): string {
        this.toXMLCheck();
        if (this._hasConvertErr()) {
            return this._renderConvertErr();
        }

        const cxml = create({ encoding: "utf-8" }).ele('cXML').dtd({
            sysID: 'http://xml.cxml.org/schemas/cXML/1.2.060/Fulfill.dtd'
        });

        // header supplier2buyer
        this._header_supplier_to_buyer(cxml);

        let request = cxml.ele(XML.Request);
        let confirmationRequest = request.ele('ConfirmationRequest');
        let eConfH = confirmationRequest.ele('ConfirmationHeader');
        let usageIndicator = this._segVal("ISA", 15);
        request.att(XML.deploymentMode, CUtilX12.usageIndicatorXML(usageIndicator));

        let BCA = this._rseg("BCA");
        let BCA01 = this._segVal(BCA, 1);
        let BCA02 = this._segVal(BCA, 2);
        switch (BCA01) {
            case "00":
                eConfH.att('operation', 'new');
                break;
            case "05":
                eConfH.att('operation', 'update');
                break;
            default:
            // wrong @operation
        }

        switch (BCA02) {
            case "AC":
                eConfH.att('type', 'detail');
                break;
            case "AE":
                eConfH.att('type', 'except');
                break;
            case "AT":
                eConfH.att('type', 'accept');
                break;
            case "RJ":
                eConfH.att('type', 'reject');
                break;
            default:
            // wrong @type
        }

        let ordRef = confirmationRequest.ele('OrderReference');
        // not mapped if REF*ON is provided
        // will be overwritten
        ordRef.att('orderID', this._segVal(BCA, 3));

        // BCA04 is ignored - @orderDate is mapped from DTM*004 - only  
        // if DTM*004 is provided with date, time and time zone
        let BCA04 = this._segVal(BCA, 4);
        let DTM004 = this._rSegByEleVal('DTM', 1, '004');
        if (DTM004) {
            ordRef.att('orderDate', Utils.dateStrFromDTM(
                this._segVal(DTM004, 2)
                , this._segVal(DTM004, 3)
                , this._segVal(DTM004, 4)
            ));
        } else {
            ordRef.att('orderDate', Utils.dateStrFromCCYYMMDD(BCA04));
        }

        // BCA08, @confirmID
        eConfH.att('confirmID', this._segVal(BCA, 8))

        // BCA09, @noticeDate, not mapped if DTM*ACK is provided
        let BCA09 = this._segVal(BCA, 9);
        let DTMACK = this._rSegByEleVal('DTM', 1, 'ACK');
        if (DTMACK) {
            eConfH.att('noticeDate', Utils.dateStrFromDTM(
                this._segVal(DTMACK, 2)
                , this._segVal(DTMACK, 3)
                , this._segVal(DTMACK, 4)
            ));
        } else {
            eConfH.att('noticeDate', Utils.dateStrFromCCYYMMDD(BCA09));
        }

        // CUR
        let CUR = this._rSegByEleVal('CUR', 1, 'BY');
        if (CUR) {
            eConfH.ele('Total').ele('Money').att(XML.currency, this._segVal(CUR, 2));
        }

        // REF
        let REFs = this._rSegs('REF');
        REFs = REFs ?? [];
        for (let REF of REFs) {
            let vREF1 = this._segVal(REF, 1);
            let vREF2 = this._segVal(REF, 2);
            switch (vREF1) {
                case 'IV':
                    eConfH.att('invoiceID', vREF2);
                    break;
                case 'ON':
                    eConfH.att('orderID', vREF2);
                    break;
                case 'CR':
                    eConfH.ele(XML.IdReference).att(XML.domain, 'CustomerReferenceID')
                        .att(XML.identifier, vREF2);
                    break;
                case 'ZB':
                    eConfH.ele(XML.IdReference).att(XML.domain, 'UltimateCustomerReferenceID')
                        .att(XML.identifier, vREF2);
                    break;
                case 'D2':
                    eConfH.ele(XML.IdReference).att(XML.domain, 'supplierReference')
                        .att(XML.identifier, vREF2);
                    break;
                case 'ZZ':
                    eConfH.ele(XML.Extrinsic).att('name', vREF2).txt(this._segVal(REF, 3));
                    break;
                default:
                    if (MAPS.mapREF128[vREF1]) {
                        eConfH.ele(XML.Extrinsic).att('name', MAPS.mapREF128[vREF1]).txt(vREF2 + this._segVal(REF, 3));
                    }

            } // end switch vREF1
        } // end loop REFs

        // FOB
        let FOB = this._rSegByEleVal('FOB', 1, 'DE');
        if (FOB) {
            let vFOB4 = this._segVal(FOB, 4);
            let vFOB5 = this._segVal(FOB, 5);
            if (vFOB4 == '01') {
                eConfH.att('incoTerms', MAPS.mapFOB335[vFOB5]);
            }
        }

        // SAC Group
        let grpSACs = this._rGrps('SAC');
        grpSACs = grpSACs ?? [];
        for (let grpSAC of grpSACs) {
            this._dealGrpSAC(grpSAC, eConfH);
        }

        // DTM
        let DTMs = this._rSegs('DTM');
        DTMs = DTMs ?? [];
        for (let DTM of DTMs) {
            let vDTM1 = this._segVal(DTM, 1);
            let vDTM2 = this._segVal(DTM, 2);
            let vDTM3 = this._segVal(DTM, 3);
            let vDTM4 = this._segVal(DTM, 4);
            if (vDTM1 == '004') {
                ordRef.att('orderDate', Utils.dateStrFromDTM(vDTM2, vDTM3, vDTM4));
            } else if (vDTM1 == 'ACK') {
                ordRef.att('noticeDate', Utils.dateStrFromDTM(vDTM2, vDTM3, vDTM4));
            }
        }

        // TXI
        let TXI = this._rSegByEleVal('TXI', 4, 'VD');
        if (TXI) {
            let vTXI_1 = this._segVal(TXI, 1);

            let eTaxD = eConfH.ele('Tax').ele('TaxDetail');
            eTaxD.att('category', MAPS.mapTXI963Category[vTXI_1])
                .ele(XML.Description).txt(MAPS.mapTXI963Desc[vTXI_1])
                .att('purpose', 'tax');
            eTaxD.ele('TaxAmount').ele('Money').txt(this._segVal(TXI, 2));
            eTaxD.att('percentageRate', this._segVal(TXI, 3));
            eTaxD.ele('TaxLocation').txt(this._segVal(TXI, 5));
            eTaxD.att('exemptDetail', this._segVal(TXI, 6));
            eTaxD.ele('TaxableAmount').ele('Money').txt(this._segVal(TXI, 8));
        }


        // N9 Group
        let grpN9s = this._rGrps('N9');
        grpN9s = grpN9s ?? [];
        for (let grpN9 of grpN9s) {
            this._dealGrpN9(grpN9, eConfH);
        }

        const xml = cxml.end({ prettyPrint: true, indent: '    ',spaceBeforeSlash: false });
        return xml;
    }

    private _dealGrpN9(grpN9: ASTNode, eConfH: XMLBuilder) {
    }

    private _dealGrpSAC(grpSAC: ASTNode, eConfH: XMLBuilder) {
        let SAC = this._dSeg1(grpSAC, 'SAC');
        let CUR = this._dSeg1(grpSAC, 'CUR');
        let vSAC1 = this._segVal(SAC, 1);
        let vSAC2 = this._segVal(SAC, 2);
        let vSAC5 = this._segVal(SAC, 5);
        let vSAC7 = this._segVal(SAC, 7);
        let vSAC12 = this._segVal(SAC, 12);
        let vCUR2 = this._segVal(CUR, 2);
        switch (vSAC2) {
            case 'G830':
                let eShipping = eConfH.ele('Shipping');
                eShipping.ele('Money').txt(this._segVal(SAC, 5))
                    .att(XML.currency, this._segVal(CUR, 2));
                eShipping.att('trackingId', this._segVal(SAC, 13));
                eShipping.att('trackingDomain', this._segVal(SAC, 14));
                eShipping.ele(XML.Description).txt(this._segVal(SAC, 15))
                    .att(XML.lang, this._segVal(SAC, 16));
                break;
            case 'H850':
                let eTax = eConfH.ele('Tax');
                eTax.ele('Money').txt(this._segVal(SAC, 5))
                    .att(XML.currency, this._segVal(CUR, 2));
                eTax.ele(XML.Description).txt(this._segVal(SAC, 15))
                    .att(XML.lang, this._segVal(SAC, 16));
                break;
            default:
                let sModName = MAPS.mapSAC1300[vSAC2];
                if (sModName) {
                    let eMods = this._ele3(eConfH, 'Total', 'Modifications');
                    let eMod = eMods.ele('Modification');
                    if (vSAC1 == 'A') {
                        let eAddDed = eMod.ele('AdditionalDeduction');
                        if (vSAC12 == '13') {
                            eAddDed.ele('DeductionAmount').ele('Money').txt(vSAC5)
                                .att(XML.currency, vCUR2);
                        } else {
                            eAddDed.ele('DeductedPrice').ele('Money').txt(vSAC5);
                        }
                        eAddDed.ele('DeductionPercent').att('percent', vSAC7);
                    } else {
                        // C Charge
                        let eAddCost = eMod.ele('AdditionalCost');
                        eAddCost.ele('Money').txt(vSAC5)
                            .att(XML.currency, vCUR2);
                        eAddCost.ele('Percentage').att('percent', vSAC7);
                    }
                    eMod.ele('OriginalPrice').ele('Money').txt(this._segVal(SAC, 13))
                        .att('type', this._segVal(SAC, 14));
                    let eModDetail = eMod.ele('ModificationDetail');
                    eModDetail.ele(XML.Description).txt(this._segVal(SAC, 15))
                        .att(XML.lang, this._segVal(SAC, 16));
                    eModDetail.att('startDate', Utils.dateStrFromDTM2(this._segVal(CUR, 8), this._segVal(CUR, 9)));
                    eModDetail.att('endDate', Utils.dateStrFromDTM2(this._segVal(CUR, 11), this._segVal(CUR, 12)));


                } // end if sModName exists
        } // end switch vSAC2


    } // end method
    private _dealGrpN1(grpN1: ASTNode, salesOrderHeader: XMLBuilder) {
        // N1
        let N1 = this._dSeg1(grpN1, 'N1');
        //let xmlContact = salesOrderHeader.ele('Contact');
        let tContact = new TidyContact();
        let roleCode = this._segVal(N1, 1) ?? 'NotExist';
        tContact.att('role', MAPS.mapN101[roleCode]);
        tContact.Name.ele('Name').txt(this._segVal(N1, 2))
            .att(XML.lang, 'EN');
        let codeQualifier = this._segVal(N1, 3) ?? 'NotExist';
        tContact.att('addressIDDomain', MAPS.mapN103[codeQualifier]);
        tContact.att('addressId', this._segVal(N1, 4));

        // N2
        let arrN2 = this._dSegs(grpN1, 'N2');
        let postalAddress = tContact.PostalAddress.ele('PostalAddress');
        for (let seg of arrN2) {
            postalAddress.ele('DeliverTo').txt(this._segVal(seg, 1));
            postalAddress.ele('DeliverTo').txt(this._segVal(seg, 2));
        }
        // N3
        let arrN3 = this._dSegs(grpN1, 'N3');
        for (let seg of arrN2) {
            postalAddress.ele('Street').txt(this._segVal(seg, 1));
            postalAddress.ele('Street').txt(this._segVal(seg, 2));
        }

        // N4
        this._X12N4(grpN1, tContact);
        tContact.sendTo(salesOrderHeader.ele('Contact'));
    } // end function _dealGrpN1
}

export class MAPS {

    static mapBEG: Object = {
        "00": "new",
        "05": "update",
        "01": "cancel",
    };
    static mapN101: Object = {
        "ST": "locationTo",
        "SU": "supplierCorporate"
    };
    static mapN103: Object = {
        "1": "DUNS",
        "2": "SCAC",
        "4": "IATA",
        "9": "DUNS+4"
    };
    static mapREF128: Object = {
        "01": "transitRoutingNumber",
        "02": "swiftID",
        "03": "chipsParticipantID",
        "04": "financialBranchAndInstitution",
        "05": "chipsUserID",
        "06": "computerManufacturerSystemID",
        "07": "addOnComputerSystemID",
        "08": "carrierPackageID",
        "09": "customsBarCodeNumber",
        "0A": "supervisoryAppraiserCertificationNo",
        "0B": "stateLicenceNumber",
        "0D": "subjectPropertyVerificationSource",
        "0E": "subjectPropertyReferenceNumber",
        "0F": "subscriberNumber",
        "0G": "reviewerFileNumber",
        "0H": "comparablePropertyPendingSaleRef",
        "0I": "comparablePropertySaleRef",
        "0J": "subjectPropertyNonSaleRef",
        "0K": "policyFormID",
        "0L": "referencedBy",
        "0M": "mortgageIdNumber",
        "0N": "attachedTo",
        "0P": "realEstateOwnedPropertyId",
        "10": "accountManagersCode",
        "11": "accountNumber",
        "12": "accountPayableID",
        "13": "horizontalCoordinate",
        "14": "masterAccountNumber",
        "15": "verticalCoordinate",
        "16": "miprNumber",
        "17": "clientReportingCategory",
        "18": "planNumber",
        "19": "divisionID",
        "1A": "blueCrossProviderNumber",
        "1B": "blueShieldProviderNumber",
        "1C": "medicareProviderNumber",
        "1D": "medicaidProviderNumber",
        "1E": "dentistLicenceNumber",
        "1F": "anesthesiaLicenceNumber",
        "1G": "providerUPINNumber",
        "1H": "champusID",
        "1I": "dodIDCode",
        "1J": "facilityID",
        "1K": "payorClaimNumber",
        "1L": "groupOrPolicyNumber",
        "1M": "ppoSiteNumber",
        "1N": "drgNumber",
        "1O": "consolidationShipmentNumber",
        "1P": "accessorialStatusCode",
        "1Q": "errorIDCode",
        "1R": "storageInfoCode",
        "1S": "ambulatoryPatientGroupNo",
        "1T": "resourceUtilizationGroupNo",
        "1U": "payGrade",
        "1V": "relatedVendorOrderNo",
        "1W": "memberIDNumber",
        "1X": "creditOrDebitAdjustmentNo",
        "1Y": "repairActionNo",
        "1Z": "financialDetailCode",
        "20": "repairPartNo",
        "21": "agaEquationNo",
        "22": "specialChargeOrAllowanceCode",
        "23": "clientNumber",
        "24": "shortTermDisabilityPolicyNo",
        "25": "reasonNotLowestCodeCode",
        "26": "unionNumber",
        "27": "InsurorPoolIDNo",
        "28": "employeeIDNo",
        "29": "foreclosureAccountNo",
        "2A": "importLicenseNo",
        "2B": "terminalReleaseOrderNo",
        "2C": "longTermDisabilityPolicyNo",
        "2D": "aeronauticalEquipmentRefNo",
        "2E": "foreignMilitarySalesCaseNo",
        "2F": "consolidatedInvoiceNo",
        "2G": "amendment",
        "2H": "assignedByTransactionSetSender",
        "2I": "trackingNo",
        "2J": "floorNo",
        "2K": "fdaProductType",
        "2L": "aarAccountingRules",
        "2M": "fccID",
        "2N": "fccTradeBrandID",
        "2O": "oshaClaimNo",
        "2P": "subdivisionID",
        "2Q": "fdaAccessionNo",
        "2R": "couponRedemptionNo",
        "2S": "catalog",
        "2T": "subSubhouseBillOfLading",
        "2U": "payerIDNumber",
        "2V": "specialGovACRN",
        "2W": "changeOrderAuthority",
        "2X": "supplementalAgreementAuthority",
        "2Y": "wageDetermination",
        "2Z": "uscsAntiDumpingDutyCaseNo",
        "30": "usGovVisaNo",
        "31": "docketNo",
        "32": "creditRepositoryCode",
        "33": "lenderCaseNo",
        "34": "loanRequestNo",
        "35": "multifamilyProjectNo",
        "36": "underwriterIDNo",
        "37": "condominiumIDNo",
        "38": "masterPolicyNo",
        "39": "proposalNo",
        "3A": "sectionOfNationalHousingActCode",
        "3B": "supplementalClaimNo",
        "3C": "payeeLoanNo",
        "3D": "servicerLoanNo",
        "3E": "investorLoanNo",
        "3F": "showID",
        "3G": "catastropheNo",
        "3H": "caseNo",
        "3I": "precinctNo",
        "3J": "officeNo",
        "3K": "petroleumPoolCode",
        "3L": "branchID",
        "3M": "fccConditionCode",
        "3N": "gasCustodianID",
        "3O": "uscsPreApprovalRulingNo",
        "3P": "thirdPartyOriginatorNo",
        "3Q": "fdaProductCode",
        "3R": "uscsBindingRulingNo",
        "3S": "provincialSalesTaxExemptionNo",
        "3T": "uscsPreClassificationRulingNo",
        "3U": "protractionNo",
        "3V": "formationID",
        "3W": "uscsCommercialDesc",
        "3X": "subcontractNo",
        "3Y": "receiverAssignedDropZone",
        "3Z": "customsBrokerRefNo",
        "40": "leaseScheduleNoReplacement",
        "41": "leaseScheduleNoPrior",
        "42": "phoneCalls",
        "43": "supportingDocumentNo",
        "44": "endUseNo",
        "45": "oldAccountNo",
        "46": "oldMeterNo",
        "47": "plateNo",
        "48": "agencysStudentNo",
        "49": "familyUnitNo",
        "4A": "personalIDNoPIN",
        "4B": "shipmentOriginCode",
        "4C": "shipmentDestinationCode",
        "4D": "shippingZone",
        "4E": "carrierAssignedConsigneeNo",
        "4F": "carrierAssignedShipperNo",
        "4G": "provincialTaxID",
        "4H": "commercialInvoiceNo",
        "4I": "balanceDueRefNo",
        "4J": "vehicleRelatedServicesRefNo",
        "4K": "accessorialRailDiversionRefNo",
        "4L": "locationSpecificServicesRefNo",
        "4M": "specialMoveRefNo",
        "4N": "specialPaymentRefNo",
        "4O": "cdnGSTorQSTRefNo",
        "4P": "affiliationNo",
        "4Q": "fccCallSign",
        "4R": "ruleSection",
        "4S": "preferredCallSign",
        "4T": "nadsID",
        "4U": "marketArea",
        "4V": "emmissionDesignator",
        "4W": "radioEngineeringStudy",
        "4X": "fccLicenseApplicationFileNo",
        "4Y": "subhouseBillOfLading",
        "4Z": "uscsCountervailingDutyCaseNo",
        "50": "stateStudentIDNo",
        "51": "pictureNo",
        "52": "swiftMT100",
        "53": "swiftMT202",
        "54": "fedWireTransfer",
        "55": "sequenceNo",
        "56": "correctedSocialSecurityNo",
        "57": "priorIncorrectSocialSecurityNo",
        "58": "correctedBatchNo",
        "59": "priorIncorrectBatchNo",
        "5A": "offenseTracking",
        "5B": "supplementalAccountNo",
        "5C": "congressionalDistrict",
        "5D": "lineOfCreditCategory",
        "5E": "consumerID",
        "5F": "warrant",
        "5G": "complaint",
        "5H": "incident",
        "5I": "offenderTracking",
        "5J": "driversLicense",
        "5K": "commercialDriversLicense",
        "5L": "juristictionalCommunityNo",
        "5M": "previousSequence",
        "5N": "citationOfStatute",
        "5O": "citationOfOpinion",
        "5P": "natlCriminalInfoCenterOrigAgencyID",
        "5Q": "stateCriminalHistRepIndividualID",
        "5R": "fbiIndividualID",
        "5S": "processingArea",
        "5T": "paymentLocation",
        "5U": "floodDataID",
        "5V": "couponDistributionMethod",
        "5W": "origUniformCommercialCodeFilingNo",
        "5X": "amdUniformCommercialCodeFilingNo",
        "5Y": "contUniformCommercialCodeFilingNo",
        "5Z": "uniformCommercialCodeFilingCollNo",
        "60": "accountSuffixCode",
        "61": "taxingAuthorityIDNo",
        "63": "priorLoanNo",
        "64": "jurisdictionalCommunityNameID",
        "65": "totalOrderCycleNo",
        "66": "previousPolicyNo",
        "67": "previousClaimHistoryID",
        "68": "dentalInsuranceAccountNo",
        "69": "dentalInsurancePolicyNo",
        "6A": "consigneeRefNo",
        "6B": "uscsEntryNo",
        "6C": "uscsEntryTypeCode",
        "6D": "uscsStatementNo",
        "6E": "mapReference",
        "6F": "appraiserLicense",
        "6G": "mapNo",
        "6H": "comparablePropertyVerificationSrc",
        "6I": "comparableProperty",
        "6J": "censusTract",
        "6K": "zone",
        "6L": "agentContractNo",
        "6M": "applicationNo",
        "6N": "claimantNo",
        "6O": "crossReferenceNo",
        "6P": "groupNo",
        "6Q": "insuranceLicenseNo",
        "6R": "providerControlNo",
        "6S": "providerOrderTicketNo",
        "6T": "pilotLicenseNo",
        "6U": "questionNo",
        "6V": "reissueCessionNo",
        "6W": "sequenceNo2",
        "6X": "specimenID",
        "6Y": "equipmentInitial",
        "6Z": "secofiNo",
        "70": "calendarNo",
        "71": "shiftNo",
        "72": "scheduleRefNo",
        "73": "statementOfWork",
        "74": "workBreakdownStructure",
        "75": "organizationBreakdownStructure",
        "76": "milestone",
        "77": "workPackage",
        "78": "planningPackage",
        "79": "costAccount",
        "7A": "poNoIncludedInOnOrderPosition",
        "7B": "poNoOfShipmentRecvSinceLastRepDate",
        "7C": "poNoOfOrderRecvSinceLastRepDate",
        "7D": "testerID",
        "7E": "collectorID",
        "7F": "repeatLocation",
        "7G": "dataQualityRejectReason",
        "7H": "epaTestTypePurposeCode",
        "7I": "subscriberAuthorizationNo",
        "7J": "tollBillingTelephoneRefNMo",
        "7K": "listOfMaterials",
        "7L": "qualifiedMaterialsList",
        "7M": "frame",
        "7N": "piggyback",
        "7O": "tripleback",
        "7P": "sheet",
        "7Q": "engineeringChangeOrder",
        "7R": "representativeIDNo",
        "7S": "drawingType",
        "7T": "masterContract",
        "7U": "relatedTransactionRefNo",
        "7W": "interchangeTrainID",
        "7X": "hmdaStateCode",
        "7Y": "hmdaCountyCode",
        "7Z": "hmdaMSA",
        "80": "chargeNo",
        "81": "symbolNumber",
        "82": "dataItemDescriptionRef",
        "83": "extendedLineItemNoELIN",
        "84": "contractorDataRequirementsListCDRL",
        "85": "subcontractorDataRequirementsSDRL",
        "86": "operationNo",
        "87": "functionalCategory",
        "88": "workCenter",
        "89": "assemblyNo",
        "8A": "hmoAuthorizationNo",
        "8B": "ppoAuthorizationNo",
        "8C": "tpoAuthorizationNo",
        "8D": "chemicalAbstractServiceRegistryNo",
        "8E": "guarantorLoanNo",
        "8F": "schoolLoanNo",
        "8G": "achTraceNo",
        "8H": "checkListNo",
        "8I": "fedwireConfirmationNo",
        "8J": "swiftConfirmationNo",
        "8K": "dominionOfCanadaCode",
        "8L": "isicCode",
        "8M": "originatingCompanyID",
        "8N": "receivingCompanyID",
        "8O": "achEntryDescription",
        "8P": "origDepositFinancialInstID",
        "8Q": "recvDepositFinancialInstID",
        "8R": "securityType",
        "8S": "brokerID",
        "8U": "bankAssignedSecurityID",
        "8V": "creditReference",
        "8W": "bankToBankInformation",
        "8X": "transactionCategoryOrType",
        "8Y": "safekeepingAccountNo",
        "8Z": "alternateClauseNo",
        "90": "subassemblyNo",
        "91": "costElement",
        "92": "changeDocumentNo",
        "93": "fundsAuthorization",
        "94": "fileIdentificationNo",
        "95": "cusipNo",
        "96": "stockCertificateNo",
        "97": "packageNo",
        "98": "containerPackagingSpecNo",
        "99": "rateConferenceIDCode",
        "9A": "repricedClaimReferenceNo",
        "9B": "repricedLineItemReferenceNo",
        "9C": "adjustedRepricedClaimReferenceNo",
        "9D": "adjustedRepricedLineItemReferenceNo",
        "9E": "replacementClaimNo",
        "9F": "referralNo",
        "9G": "dodForm250RequirementCode",
        "9H": "packagingGroupNo",
        "9I": "achStandardEntryClass",
        "9J": "pensionContract",
        "9K": "servicer",
        "9L": "serviceBureau",
        "9M": "chipsSequenceNo",
        "9N": "investor",
        "9P": "loanType",
        "9Q": "poolSuffix",
        "9R": "jobOrderNo",
        "9S": "deliveryRegion",
        "9T": "tenor",
        "9U": "loanFeatureCode",
        "9V": "paymentCategory",
        "9W": "payerCategory",
        "9X": "accountCategory",
        "9Y": "bankAssignedBankersRefNo",
        "9Z": "chamberOfCommerceNo",
        "A0": "adverstiserNo",
        "A1": "analysisTestNumber",
        "A2": "disabilityInsuranceAccountNo",
        "A3": "assignmentNo",
        "A4": "disabilityInsurancePolicyNo",
        "A5": "educationalInstutionID",
        "A6": "employeeID",
        "A7": "fsaInsuranceAccountNo",
        "A8": "fsaInsurancePolicyNo",
        "A9": "healthInsuranceAccountNo",
        "AA": "accountsReceivableStatementNo",
        "AAA": "distributorsSplitAgentNo",
        "AAB": "fundManagersReferenceNo",
        "AAC": "agencyHierarchicalLevel",
        "AAD": "officerLicenseNo",
        "AAE": "previousDistributionNo",
        "AAF": "interviewerID",
        "AAG": "militaryID",
        "AAH": "optionPolicyNo",
        "AAI": "payrollAccountNo",
        "AAJ": "priorContractNo",
        "AAK": "worksiteNo",
        "AAL": "agentNo",
        "AAM": "treatyID",
        "AAN": "associatedCaseControlNo",
        "AAO": "carrierAssignedCode",
        "AAP": "dealerNo",
        "AAQ": "directoryNo",
        "AAR": "distributorAssignedTransactionNo",
        "AAS": "distributorAssignedOrderNo",
        "AAT": "distributorsAccountNo",
        "AAU": "generalAgencyNo",
        "AAV": "laboratoryNo",
        "AAW": "agencyAssignedNo",
        "AAX": "listBillNo",
        "AAY": "accountingPeriodRef",
        "AAZ": "paramedicalID",
        "AB": "acceptableSourcePurchaserID",
        "ABA": "payrollNo",
        "ABB": "personalIDNo",
        "ABC": "policyLinkNo",
        "ABD": "secondaryPolicyNo",
        "ABE": "specialQuoteNo",
        "ABF": "natlPropertyRegistrySystemL1",
        "ABG": "natlPropertyRegistrySystemL2",
        "ABH": "investorAssignedID",
        "ABJ": "ginnieMaePoolPackageNo",
        "ABK": "mortgageElectronicRegSysOrgID",
        "ABL": "sellerLoanNo",
        "ABM": "subServicerLoanNo",
        "ABN": "natlPropertyRegistrySystemL3",
        "ABO": "stateHazardousWasteEntityID",
        "ABP": "bankruptcyProcedureNo",
        "ABQ": "natlBusinessID",
        "ABR": "priorDUNS",
        "ABS": "vesselName",
        "ABT": "securityInstrumentNo",
        "ABU": "assignmentRecordingNo",
        "ABV": "bookNo",
        "ABY": "hcfaNatlPayerID",
        "AC": "airCargoTransferManifest",
        "ACA": "growthFactorRef",
        "ACB": "region",
        "ACC": "status",
        "ACD": "classCode",
        "ACE": "serviceRequestNo",
        "ACF": "supplementNo",
        "ACG": "previousTicketNo",
        "ACH": "oneCallAgencyTicketNo",
        "ACI": "ticketNo",
        "ACJ": "billOfMaterialRevisionNo",
        "ACK": "drawingRevisionNo",
        "ACR": "achNOCCode",
        "ACS": "societyOfPropertyInfoCompilers",
        "ACT": "accountingCode",
        "AD": "acceptableSourceDUNSNo",
        "ADA": "aidar",
        "ADB": "masterPropertyNo",
        "ADC": "projectPropertyNo",
        "ADD": "unitPropertyNo",
        "ADE": "associatedPropertyNo",
        "ADF": "associatedNoForLimComElemParking",
        "ADG": "associatedNoForUnitParking",
        "ADH": "associatedNoForJoinUnitNotResub",
        "ADI": "processorID",
        "ADM": "airDimensionCode",
        "AE": "authorizationForExpenseAFENo",
        "AEA": "numeroCIN",
        "AEB": "croNumber",
        "AEC": "governmentRegistrationNo",
        "AED": "judicialNo",
        "AEE": "numeroNIT",
        "AEF": "passportNo",
        "AEG": "patronNo",
        "AEH": "registroInformacionFiscalRIF",
        "AEI": "registroUnicoDeContribuyenteRUC",
        "AEJ": "numeroSIEX",
        "AEK": "tokyoShokoResearchBusinessID",
        "AEL": "registroNacionalDeContribuyente",
        "AEM": "distributionCenterNo",
        "AF": "airlinesFlightID",
        "AG": "agentsShipmentNo",
        "AH": "masterAgreementID",
        "AHC": "airHandlingCode",
        "AI": "associatedInvoices",
        "AJ": "accountsReceivableCustomerAccount",
        "AK": "sendingCompanyAuditNo",
        "AL": "accountingEquipmentLocationNo",
        "ALC": "agencyLocationCode",
        "ALG": "titleCompanyCodeBookRef",
        "ALH": "titleDocumentSchedule",
        "ALI": "recordingNo",
        "ALJ": "titlePolicyNo",
        "ALT": "alterationNo",
        "AM": "adjustmentMemoChargeBack",
        "AN": "associatedPurchaseOrders",
        "AO": "appointmentNo",
        "AP": "accountReceivableID",
        "API": "apiDeductionCode",
        "AQ": "accessCode",
        "AR": "arrivalCode",
        "AS": "acceptableSourceSupplierID",
        "ASL": "aslbpNo",
        "ASP": "animalSpecial",
        "AST": "animalStrain",
        "AT": "appropriationNo",
        "ATC": "maintenanceAvailabilityType",
        "AU": "authorizationToMeetCompetitionNo",
        "AV": "healthInsuranceRatingAccountNo",
        "AW": "airWaybillNo",
        "AX": "governmentAccountingClassRefNo",
        "AY": "floorPlanApprovalNo",
        "AZ": "healthInsurancePolicyNo",
        "B1": "lesseeBillCodeNo",
        "B2": "axleRatio",
        "B3": "preferredProviderOrgNo",
        "B4": "bilateralCarServiceAgreements",
        "B5": "healthInsuranceRatingSuffixCode",
        "B6": "lifeInsuranceBillingAccountNo",
        "B7": "lifeInsurancePolicyNo",
        "B8": "lifeInsuranceBillingSuffixCode",
        "B9": "retirementPlanAccountNo",
        "BA": "retirementPlanPolicyNo",
        "BAA": "franchaiseTaxAccountNo",
        "BAB": "certificateOfIncorporationNo",
        "BAC": "beamAssemblyCode",
        "BAD": "stateTaxID",
        "BAE": "charterNo",
        "BAF": "receiptNo",
        "BAG": "withdrawlAccountNo",
        "BAH": "depositAccountNo",
        "BAI": "businessIdentNo",
        "BB": "authorizationNo",
        "BC": "buyersContractNo",
        "BCI": "basicContractLineItemNo",
        "BD": "bidNo",
        "BE": "businessActivity",
        "BF": "billingCenterID",
        "BG": "beginningSerialNo",
        "BH": "leaseScheduleNoBlanket",
        "BI": "bondedCarrierIRSID",
        "BJ": "carrierCustomsBondNo",
        "BK": "brokersOrderNo",
        "BKT": "bankTelegraphicNo",
        "BL": "governmentBillOfLading",
        "BLT": "billingType",
        "BM": "billOfLadingNo",
        "BMM": "beginMileMarker",
        "BN": "bookingNo",
        "BO": "binLocationNo",
        "BOI": "binaryObjectID",
        "BP": "adjustmentControlNo",
        "BQ": "healthMaintenanceOrganizationCodeNo",
        "BR": "brokerOrSalesOfficeNo",
        "BS": "splitBookingNo",
        "BT": "batchNo",
        "BU": "buyersApprovalMark",
        "BV": "purchaseOrderLineItemIDBuyer",
        "BW": "blendedWithBatchNo",
        "BX": "buyersShipmentMarkNo",
        "BY": "repairCategoryNo",
        "BZ": "complaintCode",
        "C0": "canadianSocialInsuranceNoSIN",
        "C1": "customerMaterialSpecificationNo",
        "C2": "customerProcessSpecificationNo",
        "C3": "customerSpecificationNo",
        "C4": "changeNo",
        "C5": "customerTrackingNoForLoanedMat",
        "C6": "carnetNo",
        "C7": "contractLineItemNo",
        "C8": "correctedContractNo",
        "C9": "previousCreditDebitAdjustmentNo",
        "CA": "costAllocationRef",
        "CB": "combinedShipment",
        "CBG": "censusBlockGroup",
        "CC": "contractCoOpNo",
        "CD": "creditNoteNo",
        "CDN": "citizenshipDocumentNo",
        "CE": "classOfContractCode",
        "CF": "fleetReferenceNo",
        "CG": "consigneesOrderNo",
        "CH": "customerCatalogNo",
        "CI": "uniqueConsignmentID",
        "CIR": "circuitNo",
        "CIT": "citation",
        "CJ": "clauseNo",
        "CK": "checkNo",
        "CL": "sellersCreditMemo",
        "CM": "buyersCreditMemo",
        "CMN": "continuousMoveNo",
        "CMP": "customerMaintenancePeriodSeqNo",
        "CMT": "component",
        "CN": "carrierShipmentID",
        "CNO": "commitmentNo",
        "CO": "customerOrderNo",
        "COL": "collocationIndicator",
        "COT": "certificateOfTransporation",
        "CP": "conditionOfPurchaseDocumentNo",
        "CPA": "canadianProvinceOperatingAuthNo",
        "CPT": "currentProceduralTerminologyCode",
        "CQ": "customsHouseBrokerLicenseNo",
        // "CR": "customerReferenceNo",
        "CRN": "casualtyReportNo",
        "CRS": "casualtyReportSerialNo",
        "CS": "conditionOfSaleDocumentNo",
        "CSC": "cs54KeyTrainIndicatorCode",
        "CSG": "cs54KeyTrainIndicatorGroupName",
        "CST": "censusStateCode",
        "CT": "contractNo",
        "CTS": "censusTractSuffix",
        "CU": "clearTextClause",
        "CV": "coilNo",
        "CW": "canadianWheatBoardPermitNo",
        "CX": "consignmentClassificationID",
        "CY": "commercialRegistrationNo",
        "CYC": "periodicityCode",
        "CZ": "contractRiderNo",
        "D0": "dataReliabilityCode",
        "D1": "deaOrderBlankNo",
        "D2": "supplierDocumentID",
        "D3": "natlAssocOfBoardsOfPharmacyNo",
        "D4": "cutNo",
        "D5": "dyeLotNo",
        "D6": "duplicateBillNo",
        "D7": "coverageCode",
        "D8": "lossReportNo",
        "D9": "claimNo",
        "DA": "domicileBranchNo",
        "DB": "buyersDebitMemo",
        "DC": "dealerPurchaseOrderNo",
        "DD": "documentIDCode",
        "DE": "depositorNo",
        "DF": "dfar",
        "DG": "drawingNo",
        "DH": "deaNo",
        "DHH": "hhsar",
        "DI": "distributorInvoiceNo",
        "DIS": "districtNo",
        "DJ": "deliveryTicketNo",
        "DK": "dockNo",
        "DL": "sellersDebitMemo",
        "DM": "associatedProductNo",
        "DN": "draftNo",
        "DNR": "depositNo",
        "DNS": "duns4",
        "DO": "deliveryOrderNumber",
        "DOA": "agar",
        "DOC": "car",
        "DOE": "dear",
        "DOI": "diar",
        "DOJ": "jar",
        "DOL": "dolar",
        "DON": "densityOrderNo",
        "DOS": "dosar",
        "DOT": "tar",
        "DP": "departmentNo",
        "DQ": "deliveryQuoteNo",
        "DR": "dockReceiptNo",
        "DRN": "drainholeNo",
        "DS": "dpasPriorityRating",
        "DSC": "departureFromSpecClassCode",
        "DSI": "departureFromSpecNo",
        "DST": "departureFromSpecTypeCode",
        "DT": "downstreamShipperContractNo",
        "DTS": "tapr",
        "DU": "dependentsInformation",
        "DUN": "duns",
        "DV": "diversionAuthorityNo",
        "DW": "depositSequenceNo",
        "DX": "departmentAgencyNo",
        "DY": "dodTransportationServiceCodeNo",
        "DZ": "crnaProviderID",
        "E1": "emergencyOrderNo",
        "E2": "partCausingRepairNo",
        "E3": "expansionOnEffectOfChangeNo",
        "E4": "chargeCardNo",
        "E5": "claimantsClaimNo",
        "E6": "backoutProcedureCode",
        "E7": "serviceBulletinNo",
        "E8": "serviceContractNo",
        "E9": "attachmentCode",
        "EA": "medicalRecordID",
        "EB": "embargoPermitNo",
        "EC": "circular",
        "ED": "exportDeclaration",
        "EDA": "edar",
        "EE": "electionDistrict",
        "EF": "electronicFundsTransferID",
        "EG": "endingSerialNo",
        "EH": "financialClassificationCode",
        "EI": "employersID",
        "EJ": "patientAccountNo",
        "EK": "hmsaFacilityID",
        "EL": "electronicDevicePIN",
        "EM": "electronicPaymentRefNo",
        "EMM": "endMileMarker",
        "EN": "embargoNo",
        "END": "endorsementNo",
        "EO": "submitterID",
        "EP": "exportPermitNo",
        "EPA": "epaAcquisitionRegulationEPAAR",
        "EPB": "epaTransporterID",
        "EQ": "equipmentNo",
        "ER": "containerOrEquipmentReceiptNo",
        "ES": "employersSocialSecurityNo",
        "ESN": "estimateSequenceNo",
        "ET": "excessTransportation",
        "EU": "endUsersPurchaseOrderNo",
        "EV": "receiverID",
        "EW": "mammographyCertNo",
        "EX": "estimateNo",
        "EY": "receiverSubIdentificationNo",
        "EZ": "ediAgreementID",
        "F1": "versionCodeNational",
        "F2": "versionCodeLocal",
        "F3": "submissionNo",
        "F4": "facilityCertificationNo",
        "F5": "medicareVersionCode",
        "F6": "healthInsuranceClaimNoHIC",
        "F7": "newHealthInsuranceClaimNoHIN",
        // "F8": "originalReferenceNo",
        "F9": "freightPayorReferenceNo",
        "FA": "federalAcquisitionRegulationsFAR",
        "FB": "fileTransferFormNo",
        "FC": "filerCodeIssuedByCustoms",
        "FCN": "assignedContractNo",
        "FD": "filerCodeIssuedByBureauOfCustoms",
        "FE": "failureMechanismNo",
        "FF": "filmNo",
        "FG": "fundID",
        "FH": "clinicNo",
        "FI": "fileID",
        "FJ": "lineItemControlNumber",
        "FK": "finishLotNo",
        // "FL": "fineLineClassification",
        "FLZ": "floodZone",
        "FM": "fmcForwardersNo",
        "FMP": "facilityMeasurementPointNo",
        "FN": "forwardersAgentsReferenceNo",
        "FND": "finderNo",
        "FO": "drugFormularyNo",
        "FP": "forestryPermitNo",
        "FQ": "formNo",
        "FR": "freightBillNo",
        "FS": "finalSequenceNo",
        "FSN": "assignedSequenceNo",
        "FT": "foreignTradeZone",
        "FTN": "premarketNotificationNo",
        "FU": "fundCode",
        "FV": "hmoReferenceNo",
        "FW": "stateLicenseID",
        "FWC": "finalWorkCandidateNo",
        "FX": "failureAnalysisReportNo",
        "FY": "claimOfficeNo",
        "FZ": "processorsInvoiceNo",
        "G1": "priorAuthorizationNo",
        "G2": "providerCommercialNo",
        "G3": "predeterminationOfBenefitsID",
        "G4": "peerReviewOrgApprovalNo",
        "G5": "providerSiteNo",
        "G6": "payerAssignedResubmissionRefNo",
        "G7": "resubmissionReasonCode",
        "G8": "resubmissionNo",
        "G9": "secondaryEmployeeID",
        "GA": "governmentAdvanceProgress",
        "GB": "grainBlockNo",
        "GC": "governmentContractNo",
        "GD": "returnGoodsBillOfLadingNo",
        "GE": "geographicNo",
        "GF": "specialtyLicenseNo",
        "GG": "guageTicketNo",
        "GH": "identificationCardSerialNo",
        "GI": "secondaryProviderNo",
        "GJ": "cornboreCertificationNo",
        "GK": "thirdPartyReferenceNo",
        "GL": "geographicDestinationZoneNo",
        "GM": "loanAcquisitionNo",
        "GN": "folderNo",
        "GO": "exhibitID",
        "GP": "governmentPriorityNo",
        "GQ": "internalPurchaseOrderReleaseNo",
        "GR": "grainOrderReferenceNo",
        "GS": "generalServicesAdmissionRegulations",
        "GT": "gstID",
        "GU": "internalPurchaseOrderItemNo",
        "GV": "thirdPartyPurchaseOrderNo",
        "GW": "thirdPartyPurchaseOrderReleaseNo",
        "GWS": "groupWorkCandidateSequenceNo",
        "GX": "thirdPartyPurchaseOrderItemNo",
        "GY": "emptyRepositioningNo",
        "GZ": "generalLedgerNo",
        "H1": "highFabricationAuthorizationNo",
        "H2": "highRawMaterialAuthorizationNo",
        "H3": "gravitySourceMeterNo",
        "H4": "federalInfoResourcesMgmtRegulation",
        "H5": "specialClause",
        "H6": "qualityClause",
        "H7": "standardClause",
        "H8": "hmdaCensusTract",
        "H9": "paymentHistoryReferenceNo",
        "HA": "competentAuthority",
        "HB": "billAndHoldInvoiceNo",
        "HC": "heatCode",
        "HD": "deptOfTransportHazardousNo",
        "HE": "hazardousExemptionNo",
        "HF": "engineeringDataList",
        "HG": "civilActionNo",
        "HH": "fiscalCode",
        "HHT": "typeOfHouseholdGoodsCode",
        "HI": "healthIndustryNoHIN",
        "HJ": "identityCardNo",
        "HK": "judgementNo",
        "HL": "sirenNo",
        "HM": "siretNo",
        "HMB": "hmdaBlockNumberArea",
        "HN": "hazardousCertificationNo",
        "HO": "shippersHazardousNo",
        "HP": "packAndHoldInvoiceNo",
        "HPI": "hcfaNatlProviderID",
        "HQ": "reinsuranceReference",
        "HR": "horsepowerRatingOfEngine",
        "HS": "harmonizedCodeSystemCanada",
        "HT": "codeOfFederalRegulations",
        "HU": "typeOfEscrowNo",
        "HUD": "deptOfHousingAndUrbanDevAcqReg",
        "HV": "escrowFileNo",
        "HW": "highWideFileNo",
        "HX": "autoLossItemNo",
        "HY": "propertyLossItemNo",
        "HZ": "taxAgencyNo",
        "I1": "owningBureauID",
        "I2": "iccAccountNo",
        "I3": "nonAmericanID",
        "I4": "creditCounselingID",
        "I5": "invoiceID",
        "I7": "creditReportNo",
        "I8": "socialInsuranceNo",
        "I9": "pollutant",
        "IA": "internalVendorNo",
        "IB": "inBondNo",
        "IC": "inboundToParty",
        "ICD": "icd9CM",
        "ID": "insuranceCertificateNo",
        "IE": "interchangeAgreementNo",
        "IF": "issueNo",
        "IFT": "intlFuelTaxAgreementAccountNo",
        "IG": "insurancePolicyNo",
        "IH": "initialDealerClaimNo",
        "II": "initialSampleInspectionReportNo",
        "IID": "imageID",
        "IJ": "sicCode",
        "IK": "manufacturerInvoiceID",
        // "IL": "internalOrderID",
        "IM": "imoNo",
        "IMP": "integratedMasterPlanIMP",
        "IMS": "integratedMasterScheduleIMS",
        "IN": "consigneesInvoiceNo",
        "IND": "investigatorialNewDrugNo",
        "IO": "inboundToOrOutboundFromParty",
        "IP": "inspectionReportNo",
        "IQ": "endItem",
        "IR": "intraPlantRouting",
        "IRN": "importersRefNoToLetterOfCredit",
        "IRP": "intlRegistrationPlanAccountNo",
        "IS": "invoiceNoSuffix",
        "ISC": "isicDominionOfCanadaCode",
        "ISN": "intlRegistrationPlanStickerNo",
        "ISS": "inspectionAndSurveySeqNo",
        "IT": "internalCustomerNo",
        "IU": "bargePermitNo",
        // "IV": "sellersInvoiceID",
        "IW": "partInterchangeability",
        "IX": "itemNo",
        "IZ": "insuredParcelPostNo",
        "J0": "proceeding",
        "J1": "creditor",
        "J2": "attorney",
        "J3": "judge",
        "J4": "trustee",
        "J5": "originatingCase",
        "J6": "adversaryCase",
        "J7": "leadCase",
        "J8": "jointlyAdministeredCase",
        "J9": "substantivelyConsolidatedCase",
        "JA": "beginningJobSeqNo",
        "JB": "jobProjectNo",
        "JC": "review",
        "JD": "userIdentification",
        "JE": "endingJobSequenceNo",
        "JF": "automatedUnderwritingRefNo",
        "JH": "tag",
        "JI": "multipleListingServiceArea",
        "JK": "multipleListingServiceSubArea",
        "JL": "packet",
        "JM": "multipleListingServiceMapXCoord",
        "JN": "multipleListingServiceMapYCoord",
        "JO": "multipleListingNo",
        "JP": "multipleListingServiceBookType",
        "JQ": "elevation",
        "JR": "propertyComponentLocation",
        "JS": "jobSequenceNo",
        "JT": "priorTaxIDTIN",
        "JU": "priorPhoneNo",
        "JV": "priorHealthIndustryNo",
        "JW": "priorUniversalProviderIDUPIN",
        "JX": "priorPostalZipCode",
        "JY": "originOfShipmentHarmonizedBasedCode",
        "JZ": "governingClassCode",
        "K0": "approvalCode",
        "K1": "foreignMilitarySalesNoticeNo",
        "K2": "certifiedMailNo",
        "K3": "registeredMailNo",
        "K4": "criticalityDesignator",
        "K5": "taskOrder",
        "K6": "purchaseDescription",
        "K7": "paragraphNo",
        "K8": "projectParagraphNo",
        "K9": "inquiryRequestNo",
        "KA": "distributionList",
        "KB": "beginningKanbanSerialNo",
        "KC": "exhibitDistributionList",
        "KD": "specialInstructionsNo",
        "KE": "endingKanbanSerialNo",
        "KG": "foreclosingStatus",
        "KH": "typeOfLawSuit",
        "KI": "typeOfOutstandingJudgment",
        "KJ": "taxLienJurisdiction",
        "KK": "deliveryReference",
        "KL": "contractReference",
        "KM": "rentalAccountNo",
        "KN": "censusAutomatedFilesID",
        "KO": "customsDrawbackEntryNo",
        "KP": "healthCertificateNo",
        "KQ": "procuringAgency",
        "KR": "responseToARequestForQuoteRef",
        "KS": "socicitation",
        "KT": "requestForQuotationRef",
        "KU": "officeSymbol",
        "KV": "distributionStatementCode",
        "KW": "certification",
        "KX": "representation",
        "KY": "siteSpecificProceduresTermsConds",
        "KZ": "masterSolicitationProcsTermsConds",
        "L1": "lettersOrNotes",
        "L2": "locationOnProductCode",
        "L3": "laborOperationNo",
        "L4": "proposalParagraphNo",
        "L5": "subExhibitLineItemNo",
        "L6": "subContractLineItemNo",
        "L7": "customersReleaseNo",
        "L8": "consigneesReleaseNo",
        "L9": "customersPartNo",
        "LA": "shippingLabelSerialNo",
        "LB": "lockbox",
        "LC": "leaseNo",
        "LD": "loanNo",
        "LE": "lenderEntityNo",
        "LEN": "locationExceptionOrderNo",
        "LF": "assemblyLineFeedLocation",
        "LG": "leaseScheduleNo",
        "LH": "longitudeExpressedInSeconds",
        "LI": "lineItemIDSellers",
        "LIC": "hibccLIC",
        "LJ": "localJurisdiction",
        "LK": "longitudeExpressedInDMS",
        "LL": "latitudeExpressedInSeconds",
        "LM": "prodPeriodForWhichLaborCostsAreFirm",
        "LN": "nonPickupLimitedTariffNo",
        "LO": "loadPlanningNo",
        "LOI": "loinc",
        "LP": "forPickupLimitedFreightTariffNo",
        "LQ": "latitudeExpressedInDMS",
        "LR": "localStudentID",
        "LS": "barCodedSerialNo",
        "LSD": "logisticsSupportDocTypeCode",
        "LT": "lotNo",
        "LU": "locationNo",
        "LV": "licensePlateNo",
        "LVO": "levyingOfficerID",
        "LW": "locationWithinEquipment",
        "LX": "qualifiedProductsList",
        "LY": "destOfShipmentHarmonizedBasedCode",
        "LZ": "lenderAccountNo",
        "M1": "materialStorageLocation",
        "M2": "majorForceProgram",
        "M3": "cropYear",
        "M5": "leaseAgreementAmendmentNoMaster",
        "M6": "militaryOrdnanceSecurityRiskNo",
        "M7": "medicalAssistanceCategory",
        "M8": "limitedPartnershipID",
        "M9": "taxShelterNo",
        // "MA": "shipNoticeID",
        "MB": "masterBillOfLading",
        "MBX": "mailbox",
        "MC": "microfilmNo",
        "MCI": "motorCarrierID",
        "MD": "magazineCode",
        "MDN": "hazardousWasteManifestDocNo",
        "ME": "messageAddressOrID",
        "MF": "manufacturersPartNo",
        "MG": "meterNo",
        "MH": "manufacturingOrderNo",
        "MI": "millOrderNo",
        "MJ": "modelNo",
        "MK": "manifestKeyNo",
        "ML": "militaryRankCivilianPayGardeNo",
        "MM": "masterLeaseAgreementNo",
        "MN": "micrNo",
        "MO": "manufacturingOperationNo",
        "MP": "multiplePOsOfAnInvoice",
        "MQ": "meterProvingReportNo",
        "MR": "merchandiseTypeCode",
        "MS": "manufacturerMaterialSafetyDataSheet",
        "MSL": "mailSlot",
        "MT": "meterTicketNo",
        "MU": "milspecNo",
        "MV": "migrantNo",
        "MW": "miltaryCallNo",
        "MX": "materialChangeNoticeNo",
        "MY": "modelYearNo",
        "MZ": "maintenanceRequestNo",
        "MZO": "multipleZoneOrderNo",
        "N0": "nominationNo",
        "N1": "localSchoolCourseNo",
        "N2": "localSchoolDistrictCourseNo",
        "N3": "statewideCourseNo",
        "N4": "usDoENCESCourseNo",
        "N5": "providerPlanNetworkID",
        "N6": "planNetworkID",
        "N7": "facilityNetworkID",
        "N8": "secondaryHealthInsuranceID",
        "N9": "dataAuthenticationNo",
        "NA": "northAmericanHazardousClass",
        "NAS": "nasaFARSupplement",
        "NB": "letterOfCreditNo",
        "NC": "secondaryCoverageCompanyNo",
        "ND": "letterOfCreditDraftNo",
        "NDA": "abbreviatedNewDrugApplicationNo",
        "NDB": "newDrugApplicationNo",
        "NE": "leaseRiderNo",
        "NF": "naicCode",
        "NFC": "natlFloodInsuranceProgCommunityName",
        "NFD": "natlFloodInsuranceProgCounty",
        "NFM": "natlFloodInsuranceProgMapNo",
        "NFN": "natlFloodInsuranceProgCommunityNo",
        "NFS": "natlFloodInsuranceProgState",
        "NG": "naturalGasPolicyActCategoryCode",
        "NH": "rateCardNo",
        "NI": "militaryStandardNoMILSTD",
        "NJ": "technicalDocumentNo",
        "NK": "priorCase",
        "NL": "technicalOrderNo",
        "NM": "discounterRegistrationNo",
        "NN": "nonconformanceReportNo",
        "NO": "noOT5AuthorityZeroMileageRate",
        "NP": "partialPaymentNo",
        "NQ": "medicaidRecipientID",
        "NR": "progressPaymentNo",
        "NS": "natlStockNo",
        "NT": "administratorsRefNo",
        "NU": "pendingCase",
        "NW": "associatedPolicyNo",
        "NX": "relatedNonconformanceNo",
        "NY": "agentClaimNo",
        "NZ": "criticalApplication",
        "O1": "outerContinentalShelfAreaCode",
        "O2": "outerContinentalShelfBlockNo",
        "O5": "ot5AuthorityCondOrRestOnCarHireRate",
        "O7": "opacTransaction",
        "O8": "originalFiling",
        "O9": "continuationFiling",
        "OA": "outletNo",
        "OB": "oceanBillOfLading",
        "OC": "oceanContainerNo",
        "OD": "originalReturnRequestReference",
        "OE": "openAndPrepaidStationListNo",
        "OF": "operatorID",
        "OG": "terminationFiling",
        "OH": "originHouse",
        "OI": "originalInvoiceNo",
        "OJ": "amendmentFiling",
        "OK": "offerGroup",
        "OL": "originalShippersBillOfLadingNo",
        "OM": "oceanManifest",
        // "ON": "dealerOrderNo",
        "OP": "originalPurchaseOrder",
        "OQ": "orderNo",
        "OR": "orderParagraphNo",
        "OS": "outboundFromParty",
        "OT": "salesAllowanceNo",
        "OU": "tariffSupplementNo",
        "OV": "tariffSuffixNo",
        "OW": "serviceOrderNo",
        "OX": "statementNo",
        "OZ": "productNo",
        "P1": "previousContractNo",
        "P2": "previousDEANo",
        "P3": "previouscCustomerReferenceNo",
        "P4": "projectCode",
        "P5": "positionCode",
        "P6": "pipelineNo",
        "P7": "productLineNo",
        "P8": "pickupReferenceNo",
        "P9": "pageNo",
        "PA": "priceAreaNo",
        "PAC": "patentCooperationTreatyApplNo",
        "PAN": "nonProvisionalPatentApplicationNo",
        "PAP": "provisionalPatentApplicationNo",
        "PB": "payersFinancialInstAccountNo",
        "PC": "productionCode",
        "PCC": "poolContractCode",
        "PCN": "protocolNo",
        "PD": "promotionDealNo",
        "PDL": "previousDriversLicense",
        "PE": "plantNo",
        "PF": "primeContractorContractNo",
        "PG": "productGroup",
        "PGC": "packingGroupCode",
        "PGN": "plugNo",
        "PGS": "proposedGroupWorkCandidateSeqNo",
        "PH": "priorityRating",
        "PHC": "procssHandlingCode",
        "PI": "priceListChangeOrIssueNo",
        "PID": "programID",
        "PIN": "platformID",
        "PJ": "packerNo",
        "PK": "packingListNo",
        "PL": "priceListNo",
        "PLA": "productLicensingAgreementNo",
        "PLN": "proposedContractNo",
        "PM": "partNo",
        "PMN": "premarketApplicationNo",
        "PN": "permitNo",
        "PNN": "patentNo",
        "PO": "purchaseOrderID",
        "POL": "policyNo",
        "PP": "purchaseOrderRevisionNo",
        "PQ": "payeeID",
        "PR": "priceQuoteNo",
        "PRS": "previouslyReportedSocialSecurityNo",
        "PRT": "productType",
        "PS": "purchaseOrderNumberSuffix",
        "PSI": "prevShipmentIDContinuousMove",
        "PSL": "nextShipmentIDContinuousMove",
        "PSM": "creditCard",
        "PSN": "proposedSequenceNo",
        "PT": "purchaseOptionAgreement",
        "PTC": "patentType",
        "PU": "previousBillOfLadingNo",
        "PV": "productChagneInformationNo",
        "PW": "priorPurchaseOrderNo",
        "PWC": "preliminaryWorkCandidateNo",
        "PWS": "proposedWorkCandidateSeqNo",
        "PX": "previousInvoiceNo",
        "PY": "accountID",
        "PZ": "productChagneNoticeNo",
        "Q1": "quoteNo",
        "Q2": "startingPackageNo",
        "Q3": "endingPackageNo",
        "Q4": "priorIdentifierNo",
        "Q5": "propertyControlNo",
        "Q6": "recallNo",
        "Q7": "receiverClaimNo",
        "Q8": "registrationNo",
        "Q9": "repairOrderNo",
        "QA": "pressID",
        "QB": "pressFormID",
        "QC": "productSpecificationDocumentNo",
        "QD": "replacementDEANo",
        "QE": "replacementCustomerRefNo",
        "QF": "qualityDispositionAreaID",
        "QG": "replacementAssemblyModelNo",
        "QH": "replacementassemblySerialNo",
        "QI": "qualityInspectionAreaID",
        "QJ": "returnMaterialAuthorizationNo",
        "QK": "salesProgramNo",
        "QL": "serviceAuthorizationNo",
        "QM": "qualityReviewMaterialCribID",
        "QN": "stopSequenceNo",
        "QO": "serviceEstimateNo",
        "QP": "substitutePartNo",
        "QQ": "unitNo",
        "QR": "qualityReportNo",
        "QS": "warrantyCoverageCode",
        "QT": "warrantyRegistrationNo",
        "QU": "changeVerificationProcedureCode",
        "QV": "newSysteAffectedCode",
        "QW": "newPartNo",
        "QX": "oldPartNo",
        "QY": "servicePerformedCode",
        "QZ": "referenceDrawingNo",
        "R0": "regiristoFederalDeContribuyentes",
        "R1": "currentRevsionNo",
        "R2": "cancelledRevisionNo",
        "R3": "correctionNo",
        "R4": "tariffSectionNo",
        "R5": "tariffPageNo",
        "R6": "tarriffRuleNo",
        "R7": "accountsReceivableOpenItem",
        "R8": "rentalAgreementNo",
        "R9": "rejectionNo",
        "RA": "repetitiveCargoShipmentNo",
        "RAA": "restrictedAvailabilityAuthorization",
        "RAN": "restrictedAvailabilityNo",
        "RB": "rateCodeNo",
        "RC": "railRoutingCode",
        "RD": "reelNo",
        "RE": "releaseNo",
        "REC": "relatedCase",
        "RF": "exportReferenceNo",
        "RG": "routeOrderNumberDomestic",
        "RGI": "regulatoryGuidelineID",
        "RH": "routeOrderNumberExport",
        "RI": "releaseInvoiceNoForPriorBillAndHold",
        "RIG": "rigNo",
        "RJ": "routeOrderNumberEmergency",
        "RK": "rackTypeNo",
        "RL": "reserveAssemblyLineFeedLocation",
        "RM": "rawMaterialSupplierDUNS",
        "RN": "runNo",
        "RO": "repetitiveBookingNo",
        "RP": "repetitivePatternCode",
        "RPP": "relativePriority",
        "RPT": "reportNo",
        "RQ": "purchaseRequisitionNo",
        "RR": "payersFinancialInstTransitRoutingNo",
        "RRS": "reconciliationReportSectionIDCode",
        "RS": "returnableContainerSerialNo",
        "RSN": "reservationNo",
        "RT": "bankRoutingID",
        "RU": "routeNo",
        "RV": "receivingNo",
        "RW": "repetitiveWaybillCode",
        "RX": "resubmitNo",
        "RY": "rebateNo",
        "RZ": "returnedGoodsAuthorizationNo",
        "S0": "specialApproval",
        "S1": "engineeringSpecificationNo",
        "S2": "dataSource",
        "S3": "specificationNo",
        "S4": "shippersBondNo",
        "S5": "routingInstructionNo",
        "S6": "stockNo",
        "S7": "stackTrainID",
        "S8": "sealOffNo",
        "S9": "sealOnNo",
        "SA": "salesperson",
        "SB": "salesRegionNo",
        "SBN": "suretyBondNo",
        "SC": "shipperCarOrderNo",
        "SCA": "scac",
        "SD": "subdayNo",
        "SE": "serialNumber",
        "SEK": "searchKey",
        "SES": "session",
        "SF": "shipFrom",
        "SG": "savings",
        "SH": "senderDefinedClause",
        "SHL": "shelfLifeIndicator",
        "SI": "shippersIdentifyingNoForShipmentSID",
        "SJ": "setNo",
        "SK": "serviceChangeNo",
        "SL": "salesTerritoryCode",
        "SM": "salesOfficeNo",
        "SN": "sealNo",
        "SNH": "snomed",
        "SNV": "stateNonResidentViolatorCompact",
        "SO": "shippersOrderInvoiceNo",
        "SP": "scanLine",
        "SPL": "splc",
        "SPN": "theaterScreenNo",
        "SQ": "containerSequenceNo",
        "SR": "salesResponsibility",
        "SS": "splitShipmentNo",
        "ST": "storeNo",
        "STB": "stccBridgeNo",
        "STR": "stccReplacementCode",
        "SU": "specialProcessingCode",
        "SUB": "titleReference",
        "SUO": "spacingUnitOrderNo",
        "SV": "serviceChargeNo",
        "SW": "sellersSaleNo",
        "SX": "serviceInterruptTrackingNo",
        "SY": "socialSecurityNo",
        "SZ": "specificationRevision",
        "T0": "dealerTypeID",
        "T1": "taxExchangeCode",
        "T2": "taxFormCode",
        "T3": "taxScheduleCode",
        "T4": "defenseFuelSupplyCenterSignalCode",
        "T5": "trailerUseAgreements",
        "T6": "taxFiling",
        "T7": "affectedSubsystemCode",
        "T8": "descriptionOfChangeCode",
        "T9": "documentatinoAffectedNo",
        "TA": "telecomCircuitSupplementalID",
        "TB": "truckersBillOfLading",
        "TC": "vendorTerms",
        "TD": "reasonForChange",
        "TDT": "technicalDocumentationType",
        "TE": "fmcTariffNo",
        "TF": "transferNo",
        "TG": "transportationControlNoTCN",
        "TH": "transportationAccountCodeTAC",
        "TI": "tirNo",
        "TIP": "technicalInformationPackage",
        "TJ": "federalTaxID",
        "TK": "tankNo",
        "TL": "taxLicenseExemption",
        "TM": "travelManifestACIorOTR",
        "TN": "transactionReferenceNo",
        "TO": "terminalOperatorNo",
        "TOC": "typeOfComment",
        "TP": "testSpecificationNo",
        "TPN": "transponderNo",
        "TQ": "tracerActionRequestNo",
        "TR": "governmentTransportationRequest",
        "TS": "tariffNo",
        "TSN": "templateSequenceNo",
        "TT": "terminalCode",
        "TU": "trialLocationCode",
        "TV": "lineOfBusiness",
        "TW": "taxWorksheet",
        "TX": "taxExemptionID",
        "TY": "policyType",
        "TZ": "totalCycleNo",
        "U0": "consolidatorsReceiptNo",
        "U1": "regionalAccountNo",
        "U2": "term",
        "U3": "usin",
        "U4": "unpaidInstallmentReferenceNo",
        "U5": "successorAccount",
        "U6": "predecessorAccount",
        "U8": "mbsLoanNo",
        "U9": "mbsPoolNo",
        "UA": "mortgageNo",
        "UB": "unacceptableSourcePurchaserID",
        "UC": "mortgageInsuranceIndicatorNo",
        "UD": "unacceptableSourceDUNSNo",
        "UE": "secondaryCoverageCertificateNo",
        "UF": "mortgageInsuranceCompanyNo",
        "UG": "usGovTransportationControlNo",
        "UH": "mortgageRemovalNo",
        "UI": "previousCourseNo",
        "UJ": "currentOrLatestCourseNo",
        "UK": "equivalentCourseNoAtRequestingInst",
        "UL": "crossListedCourseNo",
        "UM": "quarterQuarterSectionNo",
        "UN": "unHazardousClassificationNo",
        "UO": "quarterQuarterSpotNo",
        "UP": "upstreamShipperContractNo",
        "UQ": "sectionNo",
        "UR": "unitReliefNo",
        "URL": "url",
        "US": "unacceptableSourceSupplierID",
        "UT": "unitTrain",
        "UU": "townshipNo",
        "UV": "townshipRangeNo",
        "UW": "stateSenateDistrict",
        "UX": "stateAssemlyDistrict",
        "UY": "fannieMaeLoanNo",
        "UZ": "stateLegislativeDistrict",
        "V0": "version",
        "V1": "volumePurchaseAgreementNo",
        "V2": "visaType",
        "V3": "voyageNo",
        "V4": "stateDepartmentI20FormNo",
        "V5": "stateDepartmentIAP66FormNo",
        "V6": "naftaComplianceNo",
        "V7": "judicialDistrict",
        "V8": "institutionNo",
        "V9": "subServicer",
        "VA": "vesselAgentNo",
        "VB": "vaar",
        "VC": "vendorContractNo",
        "VD": "volumeNo",
        "VE": "vendorAbbreviationCode",
        "VF": "vendorProductChangeNoticeNo",
        "VG": "vendorChangeProcedureCode",
        "VH": "countyLegislativeDistrict",
        "VI": "poolNo",
        "VJ": "investorNoteHolderID",
        "VK": "institutionNoteHolderID",
        "VL": "thirdPartyNoteHolderID",
        "VM": "ward",
        "VN": "supplierOrderID",
        "VO": "institutionLoanNo",
        "VP": "vendorProductNo",
        "VQ": "relatedContractLineItemNo",
        "VR": "vendorIDNo",
        "VS": "vendorOrderNoSuffix",
        "VT": "motorVehicleIDNo",
        "VU": "preparersVerificationNo",
        "VV": "voucher",
        "VW": "standard",
        "VX": "vatID",
        "VY": "lineSequenceNo",
        "VZ": "sponsorsReferenceNo",
        "W1": "disposalTurnInDocumentNo",
        "W2": "weaponSystemNo",
        "W3": "manufacturingDirectiveNo",
        "W4": "procurementRequestNo",
        "W5": "inspectorID",
        "W6": "federalSuppyScheduleNo",
        "W7": "commercialAndGovEntityCAGE",
        "W8": "suffix",
        "W9": "specialPackagingInstructionNo",
        "WA": "laborOrAffiliationID",
        "WB": "americanPetroleumInstututeAPIWell",
        "WC": "contractOptionNo",
        "WCS": "workCandidateSequenceNo",
        "WD": "reviewPeriodNo",
        "WDR": "withdrawlRecord",
        "WE": "wellClassificationCode",
        "WF": "locallyAssignedControlNo",
        "WG": "vendorsPreviousJobNo",
        "WH": "masterReferenceLinkNo",
        "WI": "waiver",
        "WJ": "preAwardSurvey",
        "WK": "typeOfScienceCode",
        "WL": "federalSupplyClassificationCode",
        "WM": "weightAgreementNo",
        "WN": "wellNo",
        "WO": "workOrderNo",
        "WP": "warehousePickTicketNo",
        "WQ": "interimFundingOrganizationLoanNo",
        "WR": "warehouseReceiptNo",
        "WS": "warehouseStorageLocationNo",
        "WT": "brokersReferenceNo",
        "WU": "vessel",
        "WV": "dealerID",
        "WW": "depositoryTrustCompanyID",
        "WX": "distributorsAccountID",
        "WY": "waybillNo",
        "WZ": "distributorsRepresentativeID",
        "X0": "debtorsAccount",
        "X1": "providerClaimNo",
        "X2": "specificationClassNo",
        "X3": "defectCodeNo",
        "X4": "clinicalLabImprovementAmendmentNo",
        "X5": "stateIndustrialAccidentProviderNo",
        "X6": "originalVoucherNo",
        "X7": "batchSequenceNo",
        "X8": "secondarySuffixCodeIndicator",
        "X9": "internalControlNo",
        "XA": "substituteNationalStockNo",
        "XB": "substituteManufacturersPartNo",
        "XC": "cargoControlNo",
        "XD": "subsistenceID",
        "XE": "transportationPriorityNo",
        "XF": "governmentBillOfLadingOfficeCode",
        "XG": "airlineTicketNo",
        "XH": "contractAuditorID",
        "XI": "fhlmcLoanNo",
        "XJ": "fhlmcDeafultForeclosureSpecialistNo",
        "XK": "mortgageeLoanNo",
        "XL": "insuredsLoanNo",
        "XM": "gnmaMortgageNo",
        "XN": "titleXIXID",
        "XO": "sampleNo",
        "XP": "previousCargo",
        "XQ": "pierNo",
        "XR": "railroadCommissionRecordNo",
        "XS": "gasAnalyssiSourceMeterNo",
        "XT": "toxicologyID",
        "XU": "universalTransverseMercatorNorth",
        "XV": "universalTransverseMercatorEast",
        "XW": "universalTransverseMercatorZone",
        "XX": "ratingPeriod",
        "XY": "otherUnlistedTypeOfReferenceNo",
        "XZ": "pharmacyPresciptionNo",
        "Y0": "debtor",
        "Y1": "claimAdministratorClaimNo",
        "Y2": "thirdPartyAdministratorClaimNo",
        "Y3": "contractHolderClaimNo",
        "Y4": "agencyClaimNo",
        "Y5": "deliveryTrailerManifest",
        "Y6": "sortAndSegregate",
        "Y7": "processingArea2",
        "Y8": "userID",
        "Y9": "currentCertificateNo",
        "YA": "priorCertificateNo",
        "YB": "revisionNo",
        "YC": "tract",
        "YD": "buyerID",
        "YE": "railroadCommissionOilNo",
        "YF": "lesseeID",
        "YH": "operatorAssignedUnitNo",
        "YI": "refinerID",
        "YJ": "revenueSource",
        "YK": "rentPayorID",
        "YL": "allowanceRecipientID",
        "YM": "resourceScreeningReference",
        "YN": "receiversIDQualifier",
        "YO": "formation",
        "YP": "sellingArrangement",
        "YQ": "minimumRoyaltyPayorID",
        "YR": "operatorLeaseNo",
        "YS": "yardPosition",
        "YT": "reporterID",
        "YV": "participatingArea",
        "YW": "engineeringChangeProposal",
        "YX": "geographicScore",
        "YY": "geographicKey",
        "YZ": "georaphicIndex",
        "Z1": "safetyOfShipCertificate",
        "Z2": "safetyOfRadioCertificate",
        "Z3": "safetyEquipmentCertificate",
        "Z4": "civilLiabilitiesOfOilCertificate",
        "Z5": "loadLineCertificate",
        "Z6": "deratCertificate",
        "Z7": "maritimeDeclarationOfHealth",
        "Z8": "federalHousingAdministrationCaseNo",
        "Z9": "veteransAffairsCaseNo",
        "ZA": "supplier",
        // "ZB": "ultimateConsignee",
        "ZC": "connectingCarrier",
        "ZD": "familyMemberID",
        "ZE": "coalAuthorityNo",
        "ZF": "contractorEstablishmentCodeCEC",
        "ZG": "salesRepresentativeOrderNo",
        "ZH": "carrierAssignedReferenceNo",
        "ZI": "referenceVersionNo",
        "ZJ": "universalRailroadRevenueWaybillID",
        "ZK": "duplicateWaybillInRoute",
        "ZL": "duplicateWaybillNotInRoute",
        "ZM": "manufacturerNo",
        "ZN": "agencyCaseNo",
        "ZO": "makegoodCommercialLineNo",
        "ZP": "spouseTie",
        "ZQ": "nonSpouseTie",
        "ZR": "replacementSupplierNo",
        "ZS": "softwareApplicationNo",
        "ZT": "millingInTransit",
        "ZU": "field",
        "ZV": "block",
        "ZW": "area",
        "ZX": "countyCode",
        "ZY": "referencedPatternID",
    }

    static mapFOB335: Object = {
        "CFR": "cfr",
        "CIF": "cif",
        "CIP": "cip",
        "CPT": "cpt",
        "DAF": "daf",
        "DDP": "ddp",
        "DDU": "ddu",
        "DEQ": "deq",
        "DES": "des",
        "EXW": "exw",
        "FAS": "fas",
        "FCA": "fca",
        "FOB": "fob",

    }

    static mapSAC1300: Object = {
        "A040": "Access Charge",
        "A050": "AccountNumberCorrectionCharge",
        "A060": "AcidBattery",
        "A170": "Adjustment",
        "A520": "Charge",
        "A960": "Carrier",
        "B660": "Contract Allowance",
        "C300": "Discount-Special",
        "C310": "Discount",
        "D180": "FreightBasedOnDollarMinimum",
        "D240": "Freight",
        "D500": "Handling",
        "D980": "Insurance",
        "G580": "Royalties",
        "G821": "Shipping",
        "H970": "Allowance",
        "I530": "Volume Discount",
    }

    static mapTXI963Desc: Object = {
        "AA": "Stadium Tax",
        "AB": "Surtax",
        "AT": "Assessment",
        "BP": "Business Privilege Tax",
        "CA": "City Tax",
        "CB": "Threshold Tax",
        "CG": "Federal Value-added Tax (GST) on Goods",
        "CI": "City Rental Tax",
        "CP": "County/Parish Sales Tax",
        "CR": "County Rental Tax",
        "CS": "City Sales Tax",
        "CT": "County Tax",
        "CV": "Federal Value-added Tax (GST) on Services",
        "DL": "Default Labor Tax",
        "EQ": "Equipment Tax",
        "ET": "Energy Tax",
        "EV": "Environmental Tax",
        "F1": "FICA Tax",
        "F2": "FICA Medicare Tax",
        "F3": "FICA Social Security Tax",
        "FD": "Federal Tax",
        "FF": "Fuel Super Fund Tax",
        "FI": "Federal Income Tax Withholding",
        "FL": "Fuel L.U.S.T. Tax (Leaking Underground Storage Tank)",
        "FR": "Franchise Tax",
        "FS": "Fuel Spill Tax",
        "FT": "Federal Excise Tax",
        "GR": "Gross Receipts Tax",
        "GS": "Goods and Services Tax",
        "HS": "Public Health and Education Tax",
        "HT": "Handicap Tax",
        "HZ": "Hazardous Waste Tax",
        "LB": "Labor By Trade Tax",
        "LO": "Local Tax (Not Sales Tax)",
        "LS": "State and Local Sales Tax",
        "LT": "Local Sales Tax (All Applicable Sales Taxes by Taxing Authority Below the State Level)",
        "LU": "Leaky Underground Storage Tank (LUST) Tax (federal)",
        "LV": "Leaky Underground Storage Tank (LUST) Tax (state)",
        "MA": "Material Tax",
        "MN": "Minimum Tax",
        "MP": "Municipal Tax",
        "MS": "Miscellaneous State Tax",
        "MT": "Metropolitan Transit Tax",
        "OH": "Other Taxes",
        "OT": "Occupational Tax",
        "PG": "State or Provincial Tax on Goods",
        "PS": "State or Provincial Tax on Services",
        "SA": "State or Provincial Fuel Tax",
        "SB": "Secondary Percentage Tax",
        "SC": "School Tax",
        "SE": "State Excise Tax",
        "SF": "Superfund Tax",
        "SL": "State and Local Tax",
        "SP": "State/Provincial Tax",
        "SR": "State Rental Tax",
        "SS": "State Tax on Specific Labor",
        "ST": "State Sales Tax",
        "SU": "Sales and Use Tax",
        "SX": "Enhanced 911 - State Excise Tax",
        "T1": "Pre-threshold Tax",
        "T2": "Post Threshold Tax",
        "TD": "Telecommunications Device for the Deaf (TDD) Service Excise Tax",
        "TT": "Telecommunications Tax",
        "TX": "All Taxes",
        "UL": "License Tax",
        "UT": "Utility Users' Tax",
        "VA": "Value Added Tax",
        "WS": "Well Service",
        "ZA": "911-City Tax",
        "ZB": "911-County Tax",
        "ZC": "911-Excise Tax",
        "ZD": "911-State Tax",
        "ZE": "911-Tax",
        "ZZ": "Mutually Defined",
    }

    static mapTXI963Category: Object = {
        "AA": "other",
        "AB": "other",
        "AT": "other",
        "BP": "other",
        "CA": "other",
        "CB": "other",
        "CG": "gst",
        "CI": "other",
        "CP": "sales",
        "CR": "other",
        "CS": "sales",
        "CT": "other",
        "CV": "gst",
        "DL": "other",
        "EQ": "other",
        "ET": "other",
        "EV": "other",
        "F1": "other",
        "F2": "other",
        "F3": "other",
        "FD": "usage",
        "FF": "other",
        "FI": "other",
        "FL": "other",
        "FR": "other",
        "FS": "other",
        "FT": "other",
        "GR": "other",
        "GS": "gst",
        "HS": "other",
        "HT": "other",
        "HZ": "other",
        "LB": "other",
        "LO": "other",
        "LS": "other",
        "LT": "sales",
        "LU": "other",
        "LV": "other",
        "MA": "other",
        "MN": "other",
        "MP": "other",
        "MS": "other",
        "MT": "other",
        "OH": "other",
        "OT": "other",
        "PG": "other",
        "PS": "other",
        "SA": "other",
        "SB": "other",
        "SC": "other",
        "SE": "usage",
        "SF": "other",
        "SL": "other",
        "SP": "other",
        "SR": "other",
        "SS": "other",
        "ST": "sales",
        "SU": "sales",
        "SX": "other",
        "T1": "other",
        "T2": "other",
        "TD": "other",
        "TT": "usage",
        "TX": "other",
        "UL": "other",
        "UT": "usage",
        "VA": "vat",
        "WS": "other",
        "ZA": "other",
        "ZB": "other",
        "ZC": "usage",
        "ZD": "other",
        "ZE": "other",
        "ZZ": "other",
    }
}